Targeted config update
thinkshout/distro_helper pull request #1
Opened 2021-07-20 19:45 UTC by unclegcb

Adds a function that allows for low-disruption updates to config. You just pass in the config you want to update, where to find the new version, and the path to the parts of the config you want to pull in.

2021-07-20 19:47 UTC, unclegcb commented
A key use case for this one is content snippets: I strongly expect sites to update individual snippets, but what about when we want to add a new one to the system? We don't want to reset the existing values.

I think with this, we might consider a move away from "config distro". Or maybe just leave it in place as an option but try not to have it as part of our process.

2021-07-21 17:25 UTC, mariacha requested changes
One small suggestion here (documentation) and a bit of a point of discussion about the semicolons here.

I also continue to believe that there's value in using the `config_distro` option for future builds. The snapshot import method is just an overall more nuanced way to compare config and update it smartly, at least in theory. But Forum being stuck at the older version of Drush, thus not being able to use some of the helpful drush functions that the module suite provides, + some open questions about just what needs to happen with things like the snapshots and `config_distro` import really is causing a lot of headaches related to this. 

We can keep sorting out the bugs in the next distro.

2021-07-21 18:37 UTC, unclegcb commented on src/DistroHelperUpdates.php
> +   *   pass ["UUID"]. To set a Block label, you would pass ["settings:label"].
Oh, good call. I wonder if '#' would be better, since it's semi-reserved in YAML. https://stackoverflow.com/questions/9065136/allowed-characters-in-map-key-identifier-in-yaml

2021-07-21 23:46 UTC, mariacha commented on src/DistroHelperUpdates.php
> +   *   pass ["UUID"]. To set a Block label, you would pass ["settings:label"].
Yeah, although # is still technically possible, I've also never seen it, so I like that.

2021-07-22 20:13 UTC, unclegcb commented on src/DistroHelperUpdates.php
> +   *   pass ["UUID"]. To set a Block label, you would pass ["settings:label"].
done

2021-07-22 22:13 UTC, mariacha approved these changes
Sweet!

2021-07-22 22:13 UTC, merged